#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'
cookbook "ubuntu"
# cookbook 'apache2', '>= 1.0.0'
cookbook 'rvm', '~> 0.9.4'
cookbook 'postgresql', '~> 3.4.20'
# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
